## Problem Statement
Find the minimum of $f(x) =\left(\frac{\sqrt{3}}{2} (x_1−3)+\frac{1}{2}(x_2−5)\right)^2+ 5 \cdot \left((\frac{\sqrt{3}}{2} (x_2−5)−\frac{1}{2} (x_1−3)\right)^2$ using GA.


In [3]:
import sys
sys.path.append('../')
from common.GeneticAlgorithm import GeneticAlgorithm
import numpy as np
import math

def fitness_func(total_pop):
    """ Calculates fitness using the given Hyperellipsoid function f(x)
    Returns a (POP_SIZE, ) numpy array
    """       
    fitness = np.zeros(total_pop.shape[0])
    for i in range(total_pop.shape[0]):
        x_1, x_2 = total_pop[i]
        factor1 = (math.sqrt(3)/2 *(x_1-3) + 0.5*(x_2-5))**2
        factor2 = 5*(math.sqrt(3)/2 *(x_2-5) - 0.5*(x_1-3))**2
        fitness[i] = factor1+ factor2
    return fitness

# Experiment 1: crossover_idx=0

In [4]:
PARAM_SIZE = 2
POP_SIZE = 10
LOW_BOUND = -10
HIGH_BOUND = 10
NUM_GENERATIONS = 1000
genetic_alg = GeneticAlgorithm(
    PARAM_SIZE, 
    POP_SIZE, 
    LOW_BOUND, 
    HIGH_BOUND, 
    fitness_func
)
genetic_alg.crossover_idx = 0 # why is this better?
genetic_alg.run(NUM_GENERATIONS)

Generation : 0
Current Population: [[ 0.07957151  1.39787893]
 [ 5.83353218 -8.53372969]
 [ 1.38935026 -3.22953887]
 [ 3.79810207 -2.35980977]
 [-3.5228238  -8.53326147]
 [-4.00270265 -0.44596029]
 [ 9.8606668  -5.02109832]
 [ 9.25534316 -3.15683706]
 [-2.81265859 -3.4398122 ]
 [-3.41172243  1.87116827]]
Best result in current iteration 32.51747204237286 compared to overall 32.51747204237286
(array([3]), array([1]))
(4, 2)
Generation : 1
Current Population: [[ 0.07957151  1.39787893]
 [ 0.07957151  1.39787893]
 [-3.41172243  1.87116827]
 [-3.41172243  1.87116827]
 [-4.00270265 -0.44596029]
 [-4.00270265 -0.44596029]
 [-2.81265859 -3.02798379]
 [-2.81265859 -3.4398122 ]
 [ 1.38935026 -3.22953887]
 [ 3.79810207 -2.35980977]]
Best result in current iteration 32.51747204237286 compared to overall 32.51747204237286
(array([0, 1, 1, 2, 2]), array([0, 0, 1, 0, 1]))
(4, 2)
Generation : 2
Current Population: [[ 0.06765857  1.89042731]
 [ 0.07957151  1.39787893]
 [ 0.07957151  1.39787893]
 [-0.4

# Experiment 2: crossover_idx = param_size//2

In [9]:
PARAM_SIZE = 2
POP_SIZE = 10
LOW_BOUND = -10
HIGH_BOUND = 10
NUM_GENERATIONS = 1000
genetic_alg2 = GeneticAlgorithm(
    PARAM_SIZE, 
    POP_SIZE, 
    LOW_BOUND, 
    HIGH_BOUND, 
    fitness_func
)
# genetic_alg.crossover_idx = 0
genetic_alg2.run(NUM_GENERATIONS)

Generation : 0
Current Population: [[-8.3615829  -0.27541947]
 [-9.11861829  7.31949997]
 [-9.85120877 -2.58532977]
 [ 2.4923198  -6.22552344]
 [ 1.1173912  -0.70612958]
 [ 8.30064543  8.91405056]
 [ 6.2379687   2.00821986]
 [ 8.34926697  5.86195794]
 [ 8.89174868  4.21304848]
 [ 5.10818546  5.77617035]]
Best result in current iteration 5.630305779458637 compared to overall 5.630305779458637
(array([1, 3]), array([0, 1]))
(4, 2)
Generation : 1
Current Population: [[ 5.10818546  5.77617035]
 [ 6.2379687   4.12794294]
 [ 8.05509763  5.86195794]
 [ 8.34926697  5.86195794]
 [ 8.34926697  5.77617035]
 [ 8.30064543  8.91405056]
 [ 8.89174868  8.91405056]
 [ 8.89174868  4.21304848]
 [ 6.2379687   2.00821986]
 [ 1.1173912  -0.70612958]]
Best result in current iteration 5.630305779458637 compared to overall 5.630305779458637
(array([0, 1, 1, 2, 2, 3]), array([1, 0, 1, 0, 1, 0]))
(4, 2)
Generation : 2
Current Population: [[5.10818546 5.77617035]
 [6.2379687  5.49099828]
 [6.2379687  4.12794294]
