## Problem Statement
Find the minimum of the parabola $F(x) = 10 * x^2$ using Genetic Algorithm.
We can encode an individual in the population as a vector, `(x)` of size `(1,)`. \
We can also choose some artifical bounds for `(x)` \
So, $(x) = (0)$ would be the ideal individual since we know that the ideal solution is $\begin{pmatrix} x \\ F(x)\end{pmatrix} = \begin{pmatrix} 0 \\ 0\end{pmatrix}$

In [6]:
import sys
sys.path.append('../')
from common.GeneticAlgorithm import GeneticAlgorithm
import numpy as np
import math

def fitness_func(total_pop):
    """ Calculates fitness using the given function f(x) = 10 *x^2
    Returns a (POP_SIZE, ) numpy array
    """       
    fitness = 10 * np.square(total_pop)
    return fitness.flatten()

In [10]:
PARAM_SIZE = 1
POP_SIZE = 10
LOW_BOUND = -10
HIGH_BOUND = 10
NUM_GENERATIONS = 1000
genetic_alg = GeneticAlgorithm(
    PARAM_SIZE, 
    POP_SIZE, 
    LOW_BOUND, 
    HIGH_BOUND, 
    fitness_func
)
genetic_alg.crossover_idx = 0
genetic_alg.run(NUM_GENERATIONS)

Generation : 0
Current Population: [[ 3.34570423]
 [-4.53615683]
 [-4.48282158]
 [ 0.6629738 ]
 [ 3.32055982]
 [-5.12834689]
 [ 9.90034434]
 [-2.23145924]
 [ 2.54982958]
 [ 9.14653103]]
Best result in current iteration 4.395342612908165 compared to overall 4.395342612908165
(array([0, 1]), array([0, 0]))
(4, 1)
Generation : 1
Current Population: [[ 0.6629738 ]
 [ 0.86337707]
 [-1.96726409]
 [-2.23145924]
 [ 2.54982958]
 [ 2.54982958]
 [ 3.32055982]
 [ 3.32055982]
 [ 3.34570423]
 [-4.48282158]]
Best result in current iteration 4.395342612908165 compared to overall 4.395342612908165
(array([0, 1, 2]), array([0, 0, 0]))
(4, 1)
Generation : 2
Current Population: [[ 0.37176251]
 [ 0.6629738 ]
 [ 0.86337707]
 [ 1.27759   ]
 [-1.75453739]
 [-1.96726409]
 [-2.23145924]
 [-2.23145924]
 [ 2.54982958]
 [ 2.54982958]]
Best result in current iteration 1.3820736626370866 compared to overall 1.3820736626370866
(array([0, 1, 2]), array([0, 0, 0]))
(4, 1)
Generation : 3
Current Population: [[ 0.3717625